import React from 'react'
import '../App.css';
// TODO - add proptypes

const Home = props => {
	if (props.user) {
		return (
			<div className="Home">
				<p>Welcome back {props.user.firstName}!</p>
                <img id="pfp" src={props.user.photos[0].value}/>
				<div className="margins">
                    Let's plan out your trip. Click the Preferences button above to view or edit your preferences. Then head over to the "Schedules" page to view your autogenerated schedules! 
                    <br/>
                    At Planner App, planning your next trip could never be easier.
				</div>
			</div>
		)
	} else {
		return (
			<div className="Home">
				<p>Current User:</p>
				<code>
					{JSON.stringify(props)}
				</code>
			</div>
		)
	}
}

export default Home
