import React from 'react'
// TODO - add proptypes

const Home = props => {
	if (props.user) {
		return (
			<div className="Home">
				<p>Welcome back {props.user.firstName}!</p>
                <img id="pfp" src={props.user.photos[0].value}/>
				<p>
                    Let's plan out your trip. Click the Preferences button above to view or edit your preferences. Then head over to the "Schedules" page to view your autogenerated schedules! 

                    Here at Planner App, planning your next trip could never be easier.
				</p>
			</div>
		)
	} else {
		return (
			<div className="Home">
				<p>Current User:</p>
				<code>
					{JSON.stringify(props)}
				</code>
			</div>
		)
	}
}

export default Home
